Security updates from Secur0 reports

diff --git a/src/wmp b/src/wmp
--- a/src/wmp
+++ b/src/wmp
@@ -5,7 +5,7 @@
 # It will safely power off RAID disks before an emergency shutdown on AC outage.
 # The system is automatically restored after timeout or once power is back.
 
-version="v2.4.2"
+version="v2.4.3"
 
 if [ "$1" = "help" ]; then
     echo ""
@@ -46,6 +46,10 @@ elif [ "$1" = "set" ]; then
     fi
     SETTINGS="$WAKETIME"
     if [ -n "$PINGIP" ]; then
+        if [[ ! "$PINGIP" =~ ^[A-Za-z0-9._:-]+$ ]]; then
+            echo "Invalid PINGIP, please use only letters, digits, dots, hyphens and colons." >&2
+            exit 1
+        fi
         SETTINGS="$SETTINGS $PINGIP"
     fi
     sed -i "s|^ExecStart=.*|ExecStart=/usr/local/sbin/wmp-check $SETTINGS|" /etc/systemd/system/wmp.service
diff --git a/src/wmp-check b/src/wmp-check
--- a/src/wmp-check
+++ b/src/wmp-check
@@ -17,10 +17,14 @@ PINGIP=$2
 
 # New wake up call, without powering off the system.
 # This runs first, in case the battery is so low that the rest of the script cannot run!
+# Check WAKETIME is valid:
+if [[ ! "$WAKETIME" =~ ^[0-9]+$ ]]; then
+    echo "Invalid WAKETIME, not an integer! Aborting..." >&2
+    exit 1
 rtcwake -m no -s "$WAKETIME"
 
 # If there is no AC power but the system is still running, let's shut it down safely
-if ! upower -i $(upower -e | grep 'line_power') | grep -q 'online:\s*yes'; then
+if ! upower -i "$(upower -e | grep 'line_power')" | grep -q 'online:\s*yes'; then
     /usr/local/sbin/wmp-off "$WAKETIME"
     exit 0
 fi
diff --git a/src/wmp-off b/src/wmp-off
--- a/src/wmp-off
+++ b/src/wmp-off
@@ -11,6 +11,12 @@
 # A shutdown can be forced with
 # sudo wmp force <seconds>
 
+# Check that the input waketime is valid
+if [[ ! "$1" =~ ^[0-9]+$ ]]; then
+        echo "Invalid input, please enter a positive integer! Aborting..." >&2
+        exit 1
+fi
+
 echo -e "WakeMyPotato: Emergency shutdown on AC power outage!\nThe service will try to restart automatically in $1 seconds..." | wall
 echo "Emergency shutdown on AC power outage!" | systemd-cat -p 'alert' -t 'wmp'
 # Safely force unmount and power-off RAID HDDs
@@ -44,4 +50,4 @@ done
 # Safely power off the system for the specified time or until AC is back
 echo "Shutting down NOW! Scheduled boot in $1 s" | systemd-cat -p 'warning' -t 'wmp'
 echo rtcwake -m off -s $1 | systemd-cat -t 'wmp'
-rtcwake -m off -s $1
+rtcwake -m off -s "$1"
